# Generated by Django 5.1.2 on 2024-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='advisor_name',
            field=models.CharField(default='Some Name', max_length=256, verbose_name='Advisor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='advisor_phone_number',
            field=models.CharField(default='2089696988', max_length=256, verbose_name='Advisor Phone Number'),
            preserve_default=False,
        ),
    ]
