# Generated by Django 5.1.2 on 2024-11-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_advisor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256, unique=True, verbose_name='School Name')),
                ('district', models.CharField(max_length=256, verbose_name='District')),
                ('school_address', models.CharField(max_length=256, verbose_name='Address')),
                ('principal', models.CharField(max_length=256, verbose_name='Principal Name')),
                ('principal_phone', models.CharField(max_length=256, verbose_name='Emergency Contact Phone Number')),
            ],
        ),
    ]
