# Generated by Django 5.1.2 on 2024-12-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
